import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { z } from "zod/v4";
import { imageFileNames } from "./card-image-file";
import {
  apiCardSchema,
  assertUnique,
  assertValid,
  buildSeed,
  dedupeById,
  imageCardOf,
  normalize,
  rawSetSchema,
} from "./catalog-seed";
import type { FetchedCard } from "./catalog-seed";

const dataDirectory = process.env.CATALOG_DATA_DIRECTORY ?? "data";
const imageDirectory = process.env.CARD_IMAGE_DIRECTORY ?? join(dataDirectory, "images");
const missingImagesPath = join(dataDirectory, "missing-images.json");
const apiDirectory = join(dataDirectory, "api");
const outputPath =
  process.env.CATALOG_SEED_OUTPUT_PATH ?? "src/infrastructure/database/generated/catalog-seed.ts";
const cardFileSchema = z.object({
  setCode: z.string(),
  fetchedAt: z.string(),
  count: z.number().int().nonnegative(),
  cards: z.array(apiCardSchema),
});
const setPageSchema = z.object({
  items: z.array(rawSetSchema),
  total: z.number().int().nonnegative(),
  page: z.number().int().positive(),
  size: z.number().int().positive(),
  pages: z.number().int().positive(),
});
type SetPage = z.output<typeof setPageSchema>;

const dataFiles = await readdir(dataDirectory);
const apiFiles = await readdir(apiDirectory);
const fetchedCards = dedupeById(
  (
    await Promise.all(
      apiFiles
        .filter((file) => /^cards-[^.]+\.json$/.test(file))
        .sort(naturalCompare)
        .map(readCardFile),
    )
  ).flat(),
);
const setPages = await Promise.all(
  dataFiles
    .filter((file) => /^sets-page-\d+\.json$/.test(file))
    .sort(naturalCompare)
    .map(readSetPage),
);
if (fetchedCards.length === 0 || setPages.length === 0)
  throw new Error("Expected card files in data/api/ and set pages in data/.");
assertComplete(setPages, "set");
const sets = setPages.flatMap((page) => page.items);
assertUnique(sets, (cardSet) => cardSet.set_id, "set code");
const imageFiles = imageFileNames(fetchedCards.map((entry) => imageCardOf(entry.card)));
const { seed, skipped, identityConflicts } = buildSeed(
  fetchedCards.map(normalize),
  sets,
  imageFiles,
);
assertValid(seed);
const version = createHash("sha256").update(JSON.stringify(seed)).digest("hex");
await mkdir(dirname(outputPath), { recursive: true });
await writeFile(
  outputPath,
  `// Generated by scripts/generate-catalog-seed.ts. Do not edit manually.\nexport const CATALOG_SEED_VERSION = ${JSON.stringify(version)} as const;\nexport const catalogSeed = ${JSON.stringify(seed, null, 2)} as const;\n`,
);
console.log(
  `Generated ${outputPath} with ${seed.catalogCards.length} cards, ${seed.keywords.length} keywords (${version.slice(0, 12)}).`,
);
if (skipped.length > 0) {
  console.warn(
    `Skipped ${skipped.length} cards belonging to sets missing from data/sets-page-*.json.`,
  );
}
if (identityConflicts.length > 0) {
  console.warn(`${identityConflicts.length} identities look truncated but were left unmerged:`);
  for (const conflict of identityConflicts)
    console.warn(`  ${conflict.identityName} vs ${conflict.hosts.join(", ")} - ${conflict.reason}`);
}

const onDisk = new Set<string>(await readdir(imageDirectory).catch(() => []));
const missingImages = seed.cardMedia
  .filter((row) => row.imageFile !== undefined && !onDisk.has(row.imageFile))
  .map((row) => ({ cardId: row.cardId, imageFile: row.imageFile }));

await writeFile(missingImagesPath, `${JSON.stringify(missingImages, null, 2)}\n`, "utf8");

if (missingImages.length > 0) {
  console.warn(
    `${missingImages.length} cards have no image on disk, listed in ${missingImagesPath}:`,
  );
  for (const row of missingImages) console.warn(`  ${row.imageFile}`);
}

async function readCardFile(file: string): Promise<FetchedCard[]> {
  const contents = cardFileSchema.parse(
    JSON.parse(await readFile(join(apiDirectory, file), "utf8")),
  );
  if (contents.cards.length !== contents.count)
    throw new Error(`Incomplete card file ${file}: ${contents.cards.length}/${contents.count}.`);

  return contents.cards.map((card) => ({ card, fetchedAt: contents.fetchedAt }));
}
async function readSetPage(file: string): Promise<SetPage> {
  return setPageSchema.parse(JSON.parse(await readFile(join(dataDirectory, file), "utf8")));
}
function naturalCompare(left: string, right: string): number {
  return left.localeCompare(right, undefined, { numeric: true });
}
function assertComplete(pages: readonly SetPage[], label: string): void {
  if (pages.reduce((count, page) => count + page.items.length, 0) !== pages.at(0)?.total)
    throw new Error(`Incomplete ${label} pages.`);
}
