import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { parseCoreRules } from "./core-rules-parse";
import { buildCoreRulesSeed, coreRulesSeedVersion } from "./core-rules-seed";

const inputPath = process.env.CORE_RULES_TEXT_PATH ?? "data/rules/core-rules.txt";
const outputPath =
  process.env.CORE_RULES_SEED_OUTPUT_PATH ??
  "src/infrastructure/database/generated/core-rules-seed.ts";

const seed = buildCoreRulesSeed(parseCoreRules(await readFile(inputPath, "utf8")));
const version = coreRulesSeedVersion(seed);
await mkdir(dirname(outputPath), { recursive: true });
await writeFile(
  outputPath,
  `// Generated by scripts/generate-core-rules-seed.ts. Do not edit manually.\nexport const CORE_RULES_SEED_VERSION = ${JSON.stringify(version)} as const;\nexport const coreRulesSeed = ${JSON.stringify(seed, null, 2)} as const;\n`,
);
console.log(
  `Generated ${outputPath} with ${seed.coreRules.length} core rules, ${seed.coreRuleDetails.length} details, ${seed.coreRulesEditions.length} edition (${version.slice(0, 12)}).`,
);
